2022-04-16 10:13:03 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2022-04-16 10:13:04 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=1094 from 2022-04-16 02:08:09.169440)
2022-04-16 10:13:18 WARNING (MainThread) [homeassistant.config_entries] Config entry '冰柜' for broadlink integration not ready yet: [Errno -4000] Network timeout: No response received within 5s; Retrying in background
2022-04-16 10:13:18 WARNING (MainThread) [homeassistant.config_entries] Config entry 'desk' for broadlink integration not ready yet: [Errno -4000] Network timeout: No response received within 5s; Retrying in background
2022-04-16 10:13:23 WARNING (MainThread) [homeassistant.config_entries] Config entry '门口灯笼' for broadlink integration not ready yet: [Errno -4000] Network timeout: No response received within 10s; Retrying in background
2022-04-16 10:13:23 WARNING (MainThread) [homeassistant.components.broadlink.switch] Your configuration for the switch platform is deprecated. Please refer to the Broadlink documentation to catch up
2022-04-16 10:14:58 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-04-16 10:14:58 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-04-16 10:14:58 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-04-16 10:15:01 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
